# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encoder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='encoder.proto',
  package='protobrain',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rencoder.proto\x12\nprotobrain\"\x96\x01\n\x07\x45ncoder\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.protobrain.Encoder.EncoderType\x12\r\n\x05shape\x18\x02 \x03(\x05\"F\n\x0b\x45ncoderType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x14\n\x10NUMERICAL_SIMPLE\x10\x01\x12\x14\n\x10NUMERICAL_CYCLIC\x10\x02*\x05\x08\x64\x10\xf5\x03\"\x81\x01\n\rSimpleEncoder\x12\x11\n\tmin_value\x18\x01 \x01(\x02\x12\x15\n\tmax_value\x18\x02 \x01(\x02:\x02\x31\x30\x32\x46\n\x0esimple_encoder\x12\x13.protobrain.Encoder\x18\x64 \x01(\x0b\x32\x19.protobrain.SimpleEncoder\"\x81\x01\n\rCyclicEncoder\x12\x11\n\tmin_value\x18\x01 \x01(\x02\x12\x15\n\tmax_value\x18\x02 \x01(\x02:\x02\x31\x30\x32\x46\n\x0e\x63yclic_encoder\x12\x13.protobrain.Encoder\x18\x65 \x01(\x0b\x32\x19.protobrain.CyclicEncoder\"F\n\x0bSensorValue\x12\r\n\x03int\x18\x01 \x01(\x05H\x00\x12\x0f\n\x05\x66loat\x18\x02 \x01(\x02H\x00\x12\x0e\n\x04text\x18\x03 \x01(\tH\x00\x42\x07\n\x05value')
)



_ENCODER_ENCODERTYPE = _descriptor.EnumDescriptor(
  name='EncoderType',
  full_name='protobrain.Encoder.EncoderType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NUMERICAL_SIMPLE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NUMERICAL_CYCLIC', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=103,
  serialized_end=173,
)
_sym_db.RegisterEnumDescriptor(_ENCODER_ENCODERTYPE)


_ENCODER = _descriptor.Descriptor(
  name='Encoder',
  full_name='protobrain.Encoder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='protobrain.Encoder.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='protobrain.Encoder.shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENCODER_ENCODERTYPE,
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(100, 501), ],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=180,
)


_SIMPLEENCODER = _descriptor.Descriptor(
  name='SimpleEncoder',
  full_name='protobrain.SimpleEncoder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_value', full_name='protobrain.SimpleEncoder.min_value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_value', full_name='protobrain.SimpleEncoder.max_value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='simple_encoder', full_name='protobrain.SimpleEncoder.simple_encoder', index=0,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=312,
)


_CYCLICENCODER = _descriptor.Descriptor(
  name='CyclicEncoder',
  full_name='protobrain.CyclicEncoder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_value', full_name='protobrain.CyclicEncoder.min_value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_value', full_name='protobrain.CyclicEncoder.max_value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='cyclic_encoder', full_name='protobrain.CyclicEncoder.cyclic_encoder', index=0,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=444,
)


_SENSORVALUE = _descriptor.Descriptor(
  name='SensorValue',
  full_name='protobrain.SensorValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int', full_name='protobrain.SensorValue.int', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float', full_name='protobrain.SensorValue.float', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='protobrain.SensorValue.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='protobrain.SensorValue.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=446,
  serialized_end=516,
)

_ENCODER.fields_by_name['type'].enum_type = _ENCODER_ENCODERTYPE
_ENCODER_ENCODERTYPE.containing_type = _ENCODER
_SENSORVALUE.oneofs_by_name['value'].fields.append(
  _SENSORVALUE.fields_by_name['int'])
_SENSORVALUE.fields_by_name['int'].containing_oneof = _SENSORVALUE.oneofs_by_name['value']
_SENSORVALUE.oneofs_by_name['value'].fields.append(
  _SENSORVALUE.fields_by_name['float'])
_SENSORVALUE.fields_by_name['float'].containing_oneof = _SENSORVALUE.oneofs_by_name['value']
_SENSORVALUE.oneofs_by_name['value'].fields.append(
  _SENSORVALUE.fields_by_name['text'])
_SENSORVALUE.fields_by_name['text'].containing_oneof = _SENSORVALUE.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['Encoder'] = _ENCODER
DESCRIPTOR.message_types_by_name['SimpleEncoder'] = _SIMPLEENCODER
DESCRIPTOR.message_types_by_name['CyclicEncoder'] = _CYCLICENCODER
DESCRIPTOR.message_types_by_name['SensorValue'] = _SENSORVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Encoder = _reflection.GeneratedProtocolMessageType('Encoder', (_message.Message,), dict(
  DESCRIPTOR = _ENCODER,
  __module__ = 'encoder_pb2'
  # @@protoc_insertion_point(class_scope:protobrain.Encoder)
  ))
_sym_db.RegisterMessage(Encoder)

SimpleEncoder = _reflection.GeneratedProtocolMessageType('SimpleEncoder', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEENCODER,
  __module__ = 'encoder_pb2'
  # @@protoc_insertion_point(class_scope:protobrain.SimpleEncoder)
  ))
_sym_db.RegisterMessage(SimpleEncoder)

CyclicEncoder = _reflection.GeneratedProtocolMessageType('CyclicEncoder', (_message.Message,), dict(
  DESCRIPTOR = _CYCLICENCODER,
  __module__ = 'encoder_pb2'
  # @@protoc_insertion_point(class_scope:protobrain.CyclicEncoder)
  ))
_sym_db.RegisterMessage(CyclicEncoder)

SensorValue = _reflection.GeneratedProtocolMessageType('SensorValue', (_message.Message,), dict(
  DESCRIPTOR = _SENSORVALUE,
  __module__ = 'encoder_pb2'
  # @@protoc_insertion_point(class_scope:protobrain.SensorValue)
  ))
_sym_db.RegisterMessage(SensorValue)

_SIMPLEENCODER.extensions_by_name['simple_encoder'].message_type = _SIMPLEENCODER
Encoder.RegisterExtension(_SIMPLEENCODER.extensions_by_name['simple_encoder'])
_CYCLICENCODER.extensions_by_name['cyclic_encoder'].message_type = _CYCLICENCODER
Encoder.RegisterExtension(_CYCLICENCODER.extensions_by_name['cyclic_encoder'])

# @@protoc_insertion_point(module_scope)
