# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sdr.proto',
  package='protobrain',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\tsdr.proto\x12\nprotobrain\"A\n\x1fSparseDistributedRepresentation\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x0f\n\x07on_bits\x18\x02 \x03(\x05')
)




_SPARSEDISTRIBUTEDREPRESENTATION = _descriptor.Descriptor(
  name='SparseDistributedRepresentation',
  full_name='protobrain.SparseDistributedRepresentation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='protobrain.SparseDistributedRepresentation.shape', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='on_bits', full_name='protobrain.SparseDistributedRepresentation.on_bits', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['SparseDistributedRepresentation'] = _SPARSEDISTRIBUTEDREPRESENTATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SparseDistributedRepresentation = _reflection.GeneratedProtocolMessageType('SparseDistributedRepresentation', (_message.Message,), dict(
  DESCRIPTOR = _SPARSEDISTRIBUTEDREPRESENTATION,
  __module__ = 'sdr_pb2'
  # @@protoc_insertion_point(class_scope:protobrain.SparseDistributedRepresentation)
  ))
_sym_db.RegisterMessage(SparseDistributedRepresentation)


# @@protoc_insertion_point(module_scope)
