# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/snapshot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/snapshot.proto',
  package='brain',
  serialized_pb=_b('\n\x14proto/snapshot.proto\x12\x05\x62rain\"F\n\x1fSparseDistributedRepresentation\x12\x12\n\ndimensions\x18\x01 \x03(\x05\x12\x0f\n\x07on_bits\x18\x02 \x03(\x05\"Z\n\x08Snapshot\x12\'\n\x06\x63ortex\x18\x01 \x01(\x0b\x32\x17.brain.CorticalSnapshot\x12%\n\x06sensor\x18\x02 \x01(\x0b\x32\x15.brain.SensorSnapshot\"G\n\x10\x43orticalSnapshot\x12\x33\n\x03sdr\x18\x01 \x03(\x0b\x32&.brain.SparseDistributedRepresentation\"[\n\x0eSensorSnapshot\x12\x33\n\x03sdr\x18\x01 \x01(\x0b\x32&.brain.SparseDistributedRepresentation\x12\x14\n\x0c\x65ncodedValue\x18\x02 \x01(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SPARSEDISTRIBUTEDREPRESENTATION = _descriptor.Descriptor(
  name='SparseDistributedRepresentation',
  full_name='brain.SparseDistributedRepresentation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimensions', full_name='brain.SparseDistributedRepresentation.dimensions', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='on_bits', full_name='brain.SparseDistributedRepresentation.on_bits', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=101,
)


_SNAPSHOT = _descriptor.Descriptor(
  name='Snapshot',
  full_name='brain.Snapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cortex', full_name='brain.Snapshot.cortex', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensor', full_name='brain.Snapshot.sensor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=193,
)


_CORTICALSNAPSHOT = _descriptor.Descriptor(
  name='CorticalSnapshot',
  full_name='brain.CorticalSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sdr', full_name='brain.CorticalSnapshot.sdr', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=266,
)


_SENSORSNAPSHOT = _descriptor.Descriptor(
  name='SensorSnapshot',
  full_name='brain.SensorSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sdr', full_name='brain.SensorSnapshot.sdr', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encodedValue', full_name='brain.SensorSnapshot.encodedValue', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=359,
)

_SNAPSHOT.fields_by_name['cortex'].message_type = _CORTICALSNAPSHOT
_SNAPSHOT.fields_by_name['sensor'].message_type = _SENSORSNAPSHOT
_CORTICALSNAPSHOT.fields_by_name['sdr'].message_type = _SPARSEDISTRIBUTEDREPRESENTATION
_SENSORSNAPSHOT.fields_by_name['sdr'].message_type = _SPARSEDISTRIBUTEDREPRESENTATION
DESCRIPTOR.message_types_by_name['SparseDistributedRepresentation'] = _SPARSEDISTRIBUTEDREPRESENTATION
DESCRIPTOR.message_types_by_name['Snapshot'] = _SNAPSHOT
DESCRIPTOR.message_types_by_name['CorticalSnapshot'] = _CORTICALSNAPSHOT
DESCRIPTOR.message_types_by_name['SensorSnapshot'] = _SENSORSNAPSHOT

SparseDistributedRepresentation = _reflection.GeneratedProtocolMessageType('SparseDistributedRepresentation', (_message.Message,), dict(
  DESCRIPTOR = _SPARSEDISTRIBUTEDREPRESENTATION,
  __module__ = 'proto.snapshot_pb2'
  # @@protoc_insertion_point(class_scope:brain.SparseDistributedRepresentation)
  ))
_sym_db.RegisterMessage(SparseDistributedRepresentation)

Snapshot = _reflection.GeneratedProtocolMessageType('Snapshot', (_message.Message,), dict(
  DESCRIPTOR = _SNAPSHOT,
  __module__ = 'proto.snapshot_pb2'
  # @@protoc_insertion_point(class_scope:brain.Snapshot)
  ))
_sym_db.RegisterMessage(Snapshot)

CorticalSnapshot = _reflection.GeneratedProtocolMessageType('CorticalSnapshot', (_message.Message,), dict(
  DESCRIPTOR = _CORTICALSNAPSHOT,
  __module__ = 'proto.snapshot_pb2'
  # @@protoc_insertion_point(class_scope:brain.CorticalSnapshot)
  ))
_sym_db.RegisterMessage(CorticalSnapshot)

SensorSnapshot = _reflection.GeneratedProtocolMessageType('SensorSnapshot', (_message.Message,), dict(
  DESCRIPTOR = _SENSORSNAPSHOT,
  __module__ = 'proto.snapshot_pb2'
  # @@protoc_insertion_point(class_scope:brain.SensorSnapshot)
  ))
_sym_db.RegisterMessage(SensorSnapshot)


# @@protoc_insertion_point(module_scope)
