# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snapshot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='snapshot.proto',
  package='protobrain',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0esnapshot.proto\x12\nprotobrain\"F\n\x1fSparseDistributedRepresentation\x12\x12\n\ndimensions\x18\x01 \x03(\x05\x12\x0f\n\x07on_bits\x18\x02 \x03(\x05\"1\n\x07History\x12&\n\x08snapshot\x18\x01 \x03(\x0b\x32\x14.protobrain.Snapshot\"d\n\x08Snapshot\x12,\n\x06\x63ortex\x18\x01 \x01(\x0b\x32\x1c.protobrain.CorticalSnapshot\x12*\n\x06sensor\x18\x02 \x01(\x0b\x32\x1a.protobrain.SensorSnapshot\"L\n\x10\x43orticalSnapshot\x12\x38\n\x03sdr\x18\x01 \x03(\x0b\x32+.protobrain.SparseDistributedRepresentation\"`\n\x0eSensorSnapshot\x12\x38\n\x03sdr\x18\x01 \x01(\x0b\x32+.protobrain.SparseDistributedRepresentation\x12\x14\n\x0c\x65ncodedValue\x18\x02 \x01(\x02')
)




_SPARSEDISTRIBUTEDREPRESENTATION = _descriptor.Descriptor(
  name='SparseDistributedRepresentation',
  full_name='protobrain.SparseDistributedRepresentation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimensions', full_name='protobrain.SparseDistributedRepresentation.dimensions', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='on_bits', full_name='protobrain.SparseDistributedRepresentation.on_bits', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=100,
)


_HISTORY = _descriptor.Descriptor(
  name='History',
  full_name='protobrain.History',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshot', full_name='protobrain.History.snapshot', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=151,
)


_SNAPSHOT = _descriptor.Descriptor(
  name='Snapshot',
  full_name='protobrain.Snapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cortex', full_name='protobrain.Snapshot.cortex', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor', full_name='protobrain.Snapshot.sensor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=253,
)


_CORTICALSNAPSHOT = _descriptor.Descriptor(
  name='CorticalSnapshot',
  full_name='protobrain.CorticalSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sdr', full_name='protobrain.CorticalSnapshot.sdr', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=331,
)


_SENSORSNAPSHOT = _descriptor.Descriptor(
  name='SensorSnapshot',
  full_name='protobrain.SensorSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sdr', full_name='protobrain.SensorSnapshot.sdr', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encodedValue', full_name='protobrain.SensorSnapshot.encodedValue', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=429,
)

_HISTORY.fields_by_name['snapshot'].message_type = _SNAPSHOT
_SNAPSHOT.fields_by_name['cortex'].message_type = _CORTICALSNAPSHOT
_SNAPSHOT.fields_by_name['sensor'].message_type = _SENSORSNAPSHOT
_CORTICALSNAPSHOT.fields_by_name['sdr'].message_type = _SPARSEDISTRIBUTEDREPRESENTATION
_SENSORSNAPSHOT.fields_by_name['sdr'].message_type = _SPARSEDISTRIBUTEDREPRESENTATION
DESCRIPTOR.message_types_by_name['SparseDistributedRepresentation'] = _SPARSEDISTRIBUTEDREPRESENTATION
DESCRIPTOR.message_types_by_name['History'] = _HISTORY
DESCRIPTOR.message_types_by_name['Snapshot'] = _SNAPSHOT
DESCRIPTOR.message_types_by_name['CorticalSnapshot'] = _CORTICALSNAPSHOT
DESCRIPTOR.message_types_by_name['SensorSnapshot'] = _SENSORSNAPSHOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SparseDistributedRepresentation = _reflection.GeneratedProtocolMessageType('SparseDistributedRepresentation', (_message.Message,), dict(
  DESCRIPTOR = _SPARSEDISTRIBUTEDREPRESENTATION,
  __module__ = 'snapshot_pb2'
  # @@protoc_insertion_point(class_scope:protobrain.SparseDistributedRepresentation)
  ))
_sym_db.RegisterMessage(SparseDistributedRepresentation)

History = _reflection.GeneratedProtocolMessageType('History', (_message.Message,), dict(
  DESCRIPTOR = _HISTORY,
  __module__ = 'snapshot_pb2'
  # @@protoc_insertion_point(class_scope:protobrain.History)
  ))
_sym_db.RegisterMessage(History)

Snapshot = _reflection.GeneratedProtocolMessageType('Snapshot', (_message.Message,), dict(
  DESCRIPTOR = _SNAPSHOT,
  __module__ = 'snapshot_pb2'
  # @@protoc_insertion_point(class_scope:protobrain.Snapshot)
  ))
_sym_db.RegisterMessage(Snapshot)

CorticalSnapshot = _reflection.GeneratedProtocolMessageType('CorticalSnapshot', (_message.Message,), dict(
  DESCRIPTOR = _CORTICALSNAPSHOT,
  __module__ = 'snapshot_pb2'
  # @@protoc_insertion_point(class_scope:protobrain.CorticalSnapshot)
  ))
_sym_db.RegisterMessage(CorticalSnapshot)

SensorSnapshot = _reflection.GeneratedProtocolMessageType('SensorSnapshot', (_message.Message,), dict(
  DESCRIPTOR = _SENSORSNAPSHOT,
  __module__ = 'snapshot_pb2'
  # @@protoc_insertion_point(class_scope:protobrain.SensorSnapshot)
  ))
_sym_db.RegisterMessage(SensorSnapshot)


# @@protoc_insertion_point(module_scope)
