// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdr.proto

#ifndef PROTOBUF_INCLUDED_sdr_2eproto
#define PROTOBUF_INCLUDED_sdr_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sdr_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_sdr_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_sdr_2eproto();
namespace protobrain {
class SparseDistributedRepresentation;
class SparseDistributedRepresentationDefaultTypeInternal;
extern SparseDistributedRepresentationDefaultTypeInternal _SparseDistributedRepresentation_default_instance_;
}  // namespace protobrain
namespace google {
namespace protobuf {
template<> ::protobrain::SparseDistributedRepresentation* Arena::CreateMaybeMessage<::protobrain::SparseDistributedRepresentation>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace protobrain {

// ===================================================================

class SparseDistributedRepresentation :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protobrain.SparseDistributedRepresentation) */ {
 public:
  SparseDistributedRepresentation();
  virtual ~SparseDistributedRepresentation();

  SparseDistributedRepresentation(const SparseDistributedRepresentation& from);

  inline SparseDistributedRepresentation& operator=(const SparseDistributedRepresentation& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SparseDistributedRepresentation(SparseDistributedRepresentation&& from) noexcept
    : SparseDistributedRepresentation() {
    *this = ::std::move(from);
  }

  inline SparseDistributedRepresentation& operator=(SparseDistributedRepresentation&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const SparseDistributedRepresentation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SparseDistributedRepresentation* internal_default_instance() {
    return reinterpret_cast<const SparseDistributedRepresentation*>(
               &_SparseDistributedRepresentation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SparseDistributedRepresentation* other);
  friend void swap(SparseDistributedRepresentation& a, SparseDistributedRepresentation& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SparseDistributedRepresentation* New() const final {
    return CreateMaybeMessage<SparseDistributedRepresentation>(nullptr);
  }

  SparseDistributedRepresentation* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SparseDistributedRepresentation>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SparseDistributedRepresentation& from);
  void MergeFrom(const SparseDistributedRepresentation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SparseDistributedRepresentation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 shape = 1;
  int shape_size() const;
  void clear_shape();
  static const int kShapeFieldNumber = 1;
  ::google::protobuf::int32 shape(int index) const;
  void set_shape(int index, ::google::protobuf::int32 value);
  void add_shape(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      shape() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_shape();

  // repeated int32 on_bits = 2;
  int on_bits_size() const;
  void clear_on_bits();
  static const int kOnBitsFieldNumber = 2;
  ::google::protobuf::int32 on_bits(int index) const;
  void set_on_bits(int index, ::google::protobuf::int32 value);
  void add_on_bits(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      on_bits() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_on_bits();

  // @@protoc_insertion_point(class_scope:protobrain.SparseDistributedRepresentation)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > shape_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > on_bits_;
  friend struct ::TableStruct_sdr_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SparseDistributedRepresentation

// repeated int32 shape = 1;
inline int SparseDistributedRepresentation::shape_size() const {
  return shape_.size();
}
inline void SparseDistributedRepresentation::clear_shape() {
  shape_.Clear();
}
inline ::google::protobuf::int32 SparseDistributedRepresentation::shape(int index) const {
  // @@protoc_insertion_point(field_get:protobrain.SparseDistributedRepresentation.shape)
  return shape_.Get(index);
}
inline void SparseDistributedRepresentation::set_shape(int index, ::google::protobuf::int32 value) {
  shape_.Set(index, value);
  // @@protoc_insertion_point(field_set:protobrain.SparseDistributedRepresentation.shape)
}
inline void SparseDistributedRepresentation::add_shape(::google::protobuf::int32 value) {
  shape_.Add(value);
  // @@protoc_insertion_point(field_add:protobrain.SparseDistributedRepresentation.shape)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SparseDistributedRepresentation::shape() const {
  // @@protoc_insertion_point(field_list:protobrain.SparseDistributedRepresentation.shape)
  return shape_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SparseDistributedRepresentation::mutable_shape() {
  // @@protoc_insertion_point(field_mutable_list:protobrain.SparseDistributedRepresentation.shape)
  return &shape_;
}

// repeated int32 on_bits = 2;
inline int SparseDistributedRepresentation::on_bits_size() const {
  return on_bits_.size();
}
inline void SparseDistributedRepresentation::clear_on_bits() {
  on_bits_.Clear();
}
inline ::google::protobuf::int32 SparseDistributedRepresentation::on_bits(int index) const {
  // @@protoc_insertion_point(field_get:protobrain.SparseDistributedRepresentation.on_bits)
  return on_bits_.Get(index);
}
inline void SparseDistributedRepresentation::set_on_bits(int index, ::google::protobuf::int32 value) {
  on_bits_.Set(index, value);
  // @@protoc_insertion_point(field_set:protobrain.SparseDistributedRepresentation.on_bits)
}
inline void SparseDistributedRepresentation::add_on_bits(::google::protobuf::int32 value) {
  on_bits_.Add(value);
  // @@protoc_insertion_point(field_add:protobrain.SparseDistributedRepresentation.on_bits)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SparseDistributedRepresentation::on_bits() const {
  // @@protoc_insertion_point(field_list:protobrain.SparseDistributedRepresentation.on_bits)
  return on_bits_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SparseDistributedRepresentation::mutable_on_bits() {
  // @@protoc_insertion_point(field_mutable_list:protobrain.SparseDistributedRepresentation.on_bits)
  return &on_bits_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobrain

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_sdr_2eproto
